on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Linux build
jobs:
    test-ubuntu:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.8", "3.9", "3.10", "3.11"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  pip install .[all]
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
